# Site
name: "Chris KY FUNG's Page"
title: "Feel free to bookmark this to keep an eye on my project updates"
description: "Chris KY FUNG's Blog"
meta_description: "Chris KY FUNG's Blog."
logo: 'assets/images/logo-plainSVG.svg'
favicon: 'assets/images/favicon.png'
paginate: 12
paginate_path: "/blog/page:num/"
permalink: /blog/:year/:month/:day/:title
timezone: Asia/Hong_Kong
baseurl: ''
email: ''
google_analytics: 'UA-72575541-9'
disqus: 'chriskyfung'
sharethis: '<script async defer type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5d01c83d522ad580"></script>'

# Authors
authors:
  chris:
    name: Chris KY Fung
    display_name: Chris F.
    gravatar: abd876486b2caa54b43bf64a5a86f620
    email: 
    web: https://en.gravatar.com/chrisfungky
    facebook: https://www.facebook.com/chriskyfung/
    description: "Author of this blog, M.Phil."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minifier
  - jekyll-loading-lazy
        
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks: 
    category: '/category/:name/'
    tag: '/tag/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
jekyll-minifier:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns